# Launch an app EC2 Instance

- name: Launch the new EC2 Instance
  local_action: ec2 
                group={{ security_group }} 
                instance_type={{ instance_type}}
                ec2_access_key="{{ ec2_access_key }}"
                ec2_secret_key="{{ ec2_secret_key }}"
                image={{ image }} 
                wait=true 
                region={{ region }} 
                keypair={{ keypair }}
                count={{app_count}}

  register: ec2


##Wait For Start the server 

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: ec2.instances


##Add Tag to server 

- name: Add tag to Instance(s)
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present ec2_access_key="{{ ec2_access_key }}" ec2_secret_key="{{ ec2_secret_key }}"
  with_items: ec2.instances
  args:
    tags:
      Name: appserver


## Add Dynamic Inventory of App Servers for public access

- name: add inmemory hosts
  add_host: hostname={{ item.public_dns_name }} groups=appserver ansible_ssh_host={{ item.public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{ ansible_user_dir }}/aws-{{ project_name }}.pem
  with_items: ec2.instances


## Add Dynamic Inventory of App Servers for Private access
- name: add inmemory hosts
  add_host: name={{ item.private_ip }} groups=appserverint
  with_items: ec2.instances


