# Launch an Web EC2 Instance

- name: Launch the new EC2 Instance
  local_action: ec2 
                group={{ security_group }} 
                instance_type={{ instance_type}}
                ec2_access_key="{{ ec2_access_key }}"
                ec2_secret_key="{{ ec2_secret_key }}"
                image={{ image }} 
                wait=true 
                region={{ region }} 
                keypair={{ keypair }}
                count={{web_count}}

  register: ec2


## Wait For Server up

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: ec2.instances


## Add Tag to Instance
- name: Add tag to Instance(s)
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present ec2_access_key="{{ ec2_access_key }}" ec2_secret_key="{{ ec2_secret_key }}"
  with_items: ec2.instances
  args:
    tags:
      Name: webserver


## Add Dynamic host Inventory 
- name: add inmemory hosts
  add_host: hostname={{ item.public_dns_name }} groups=webserver ansible_ssh_host={{ item.public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{ ansible_user_dir }}/aws-{{ project_name }}.pem
  with_items: ec2.instances




